{
 "title": "OMNT",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "data_source",
    "label": "Data Source",
    "query": "customTagValues = (bucket, tag, predicate=(r) => true, start=v.timeRangeStart, stop=v.timeRangeStop) =>\n  from(bucket: bucket)\n    |> range(start: start, stop: stop)\n    |> filter(fn: predicate)\n    |> keep(columns: [tag])\n    |> group()\n    |> distinct(column: tag)\n\ncustomTagValues(bucket: \"${bucket}\", tag: \"measurement_name\")"
   },
   { "name": "bucket", "label": "Measurement", "query": "buckets()" },
   {
    "name": "cell_id",
    "label": "Cell ID",
    "query": "customTagValues = (bucket, tag, predicate=(r) => true, start=v.timeRangeStart, stop=v.timeRangeStop) =>\n  from(bucket: bucket)\n    |> range(start: start, stop: stop)\n    |> filter(fn: predicate)\n    |> keep(columns: [tag])\n    |> group()\n    |> distinct(column: tag)\n\ncustomTagValues(bucket: \"${bucket}\", tag: \"CI\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Geo Overview",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Location\")\n  |> filter(fn: (r) => r[\"_field\"] == \"altitude\" or r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\" or r[\"_field\"] == \"speed\")\n  |> filter(fn: (r) => r[\"measurement_name\"] == \"${data_source}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"CellInformation\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TAC\" or r[\"_field\"] == \"SSSINR\" or r[\"_field\"] == \"SSRSRQ\" or r[\"_field\"] == \"SSRSRP\" or r[\"_field\"] == \"PCI\" or r[\"_field\"] == \"OperatorAlphaLong\" or r[\"_field\"] == \"NRARFCN\" or r[\"_field\"] == \"MNC\" or r[\"_field\"] == \"Level\" or r[\"_field\"] == \"IsRegistered\" or r[\"_field\"] == \"Bands\" or r[\"_field\"] == \"CI\" or r[\"_field\"] == \"CellConnectionStatus\" or r[\"_field\"] == \"CellType\")\n  |> filter(fn: (r) => r[\"measurement_name\"] == \"${data_source}\")\n  |> filter(fn: (r) => r[\"CI\"] == \"${cell_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Location\")\n  |> filter(fn: (r) => r[\"_field\"] == \"altitude\")\n  |> filter(fn: (r) => r[\"measurement_name\"] == \"${data_source}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Location\")\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\n  |> filter(fn: (r) => r[\"measurement_name\"] == \"${data_source}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Clock", "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 2, "x": 22, "y": 11 } },
  {
   "title": "Last Timestamp (UTC)",
   "type": "table",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: 0, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Location\")\n  |> filter(fn: (r) => r[\"measurement_name\"] == \"${data_source}\")\n  |> keep(columns: [\"_time\"])\n  |> last(column: \"_time\")"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"InterfaceThroughput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"downSpeed_kbps\" or r[\"_field\"] == \"upSpeed_kbps\")\n  |> filter(fn: (r) => r[\"measurement_name\"] == \"${data_source}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"InterfaceThroughput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MobileRxBytes\" or r[\"_field\"] == \"MobileTxBytes\")\n  |> filter(fn: (r) => r[\"measurement_name\"] == \"${data_source}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: false)\n  |> map(fn: (r) => ({r with _value: r._value * 8.0}))"
    }
   ]
  },
  {
   "title": "Iperf3",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"measurement_name\"] == \"${data_source}\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Iperf3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bits_per_second\" or r[\"_field\"] == \"rtt\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Signal (Level)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"CellInformation\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Level\")\n  |> filter(fn: (r) => r[\"measurement_name\"] == \"${data_source}\")\n  |> filter(fn: (r) => r[\"CI\"] == \"${cell_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Signal (db / dBm)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"CellInformation\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SSRSRP\" or r[\"_field\"] == \"SSRSRQ\" or r[\"_field\"] == \"SSSINR\" or r[\"_field\"] == \"RSRP\" or r[\"_field\"] == \"RSRQ\" or r[\"_field\"] == \"RSSI\")\n  |> filter(fn: (r) => r[\"measurement_name\"] == \"${data_source}\")\n  |> filter(fn: (r) => r[\"CI\"] == \"${cell_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Altitude  (over NN) / Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "auto" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Location\")\n  |> filter(fn: (r) => r[\"_field\"] == \"altitude\" or r[\"_field\"] == \"speed\")\n  |> filter(fn: (r) => r[\"measurement_name\"] == \"${data_source}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"CellInformation\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TAC\" or r[\"_field\"] == \"SSSINR\" or r[\"_field\"] == \"SSRSRQ\" or r[\"_field\"] == \"SSRSRP\" or r[\"_field\"] == \"PCI\" or r[\"_field\"] == \"OperatorAlphaLong\" or r[\"_field\"] == \"NRARFCN\" or r[\"_field\"] == \"MNC\" or r[\"_field\"] == \"Level\" or r[\"_field\"] == \"IsRegistered\" or r[\"_field\"] == \"Bands\" or r[\"_field\"] == \"CI\" or r[\"_field\"] == \"CellConnectionStatus\" or r[\"_field\"] == \"CellType\")\n  |> filter(fn: (r) => r[\"measurement_name\"] == \"${data_source}\")\n  |> filter(fn: (r) => r[\"CI\"] == \"${cell_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}