LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libiperf3.10.1
LOCAL_DISABLE_FORMAT_STRING_CHECKS := true
LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/iperf3.10.1.so
include $(BUILD_SHARED_LIBRARY)
include $(CLEAR_VARS)
LOCAL_MODULE := iperf3.10.1
LOCAL_DISABLE_FORMAT_STRING_CHECKS := true
LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/iperf3.10.1.so
include $(PREBUILT_SHARED_LIBRARY)

